name: CI
on:
  push:
    branches:
    - master
    - ci/publish
  pull_request:
    branches:
    - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: ['11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          java-package: 'jdk'
          check-latest: true
          server-id: 'ossrh' # must match the serverId configured for the nexus-staging-maven-plugin
          server-username: OSSRH_USERNAME # Env var that holds your OSSRH user name
          server-password: OSSRH_PASSWORD # Env var that holds your OSSRH user pw
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: SIGN_KEY_PASS # Env var that holds the key's passphrase
          cache: 'maven'

#      - name: Build with Maven
#        run: |
#          mkdir -p ~/.groovy
#          ./mvnw --version
#          cp -f remote-test/src/test/resources/grapeConfig.xml ~/.groovy
#          ./mvnw -e -DskipIntTest=false clean install jacoco:report

      - name: Publish
        # publish snapshot only when push to master branch
        if: github.event_name == 'push'
        run: ./mvnw -U -B clean deploy -P deploy
        env:
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
